apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: redis
  # deployment labels
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  replicas: 3
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: redis
      project: roboshop
      tier: database
  # This is pod definition
  template:
    metadata:
      labels:
        component: redis
        project: roboshop
        tier: database
    spec:
      containers:
      - name: redis
        image: joindevops/redis:v1
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: redis
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  selector:
    component: redis
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port 


